spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  client-id: wutsi-shipping
  platform:
    security:
      api-key: ${API_KEY}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

