openapi: "3.0.0"
info:
  title: "Wutsi Shipping API"
  description: API for managing shipping
  version: "1.0.0"

servers:
  - url: https://wutsi-shipping-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-shipping-server-prod.herokuapp.com
    description: Production

paths:
  /v1/shippings:
    get:
      operationId: "list-shipping"
      description: Return all shipping methods
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Product
      security:
        - api_key: [ 'shipping-read' ]

    post:
      operationId: "create-shipping"
      description: Create an shipping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShippingRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]

  /v1/shippings/{id}:
    get:
      operationId: "get-shipping"
      description: Get an shipping
      parameters:
        - in: path
          name: id
          description: ID of the shipping
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-read' ]

    post:
      operationId: "update-shipping"
      description: Update a shipping method
      parameters:
        - in: path
          name: id
          description: ID of the shipping
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShippingRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]

  /v1/rates:
    post:
      operationId: "save-rate"
      description: Save shipping rate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveRateRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]

  /v1/rates/{id}:
    delete:
      operationId: "delete-rate"
      description: Delete a rate
      parameters:
        - in: path
          name: id
          description: ID of the rate
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateShippingRequest:
      type: object
      properties:
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        message:
          type: string
          description: Message to display to customer
          nullable: true

    CreateShippingResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping created

    UpdateShippingRequest:
      type: object
      properties:
        message:
          type: string
          description: Message to display to customer
          nullable: true
        enabled:
          type: boolean
          description: Enabled or Disabled

    Rate:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping rate
        country:
          type: string
          description: Coutry code
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        amount:
          type: number
          format: double
          description: rate amount

    Shipping:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping method
        accountId:
          type: integer
          format: int64
          description: ID of the merchant
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        message:
          type: string
          description: Message to display to customer
          nullable: true
        enabled:
          type: boolean
          description: Enabled or Disabled
        rates:
          type: array
          items:
            $ref: "#/components/schemas/Rate"

    GetShippingResponse:
      type: object
      properties:
        shipping:
          type: object
          $ref: "#/components/schemas/Shipping"

    ShippingSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping method
        accountId:
          type: integer
          format: int64
          description: ID of the merchant
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        enabled:
          type: boolean
          description: Enabled or Disabled

    ListShippingResponse:
      type: object
      properties:
        shippings:
          type: array
          items:
            $ref: "#/components/schemas/ShippingSummary"

    SaveRateRequest:
      type: object
      properties:
        shippingId:
          type: integer
          format: int64
          description: ID of the shipping
        country:
          type: string
          description: Coutry code
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        amount:
          type: number
          format: double
          description: Shipping rate
