openapi: "3.0.0"
info:
  title: "Wutsi Shipping API"
  description: API for managing shipping
  version: "1.0.0"

servers:
  - url: https://wutsi-shipping-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-shipping-server-prod.herokuapp.com
    description: Production

paths:
  /v1/shippings:
    get:
      operationId: "list-shipping"
      description: Return all shipping methods
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
      tags:
        - Product
      security:
        - api_key: [ 'shipping-read' ]

    post:
      operationId: "create-shipping"
      description: Create an shipping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShippingRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]

  /v1/shippings/{id}:
    get:
      operationId: "get-shipping"
      description: Get an shipping
      parameters:
        - in: path
          name: id
          description: ID of the shipping
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetShippingResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-read' ]

  /v1/shippings/{id}/attributes/{name}:
    post:
      operationId: "update-shipping-attribute"
      description: Update a shipping method
      parameters:
        - in: path
          name: id
          description: ID of the shipping
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: name
          description: name of the attributes
          required: true
          schema:
            type: string
            enum:
              - enabled
              - message
              - rate
              - delivery-time
              - country
              - city-id
              - zip-code
              - street
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShippingAttributeRequest'
      responses:
        200:
          description: Success
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-manage' ]


  /v1/rates/search:
    post:
      operationId: "search-rate"
      description: Search for shipping rates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRateRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchRateResponse'
        403:
          description: The caller is not authorized to call this endpoint
        409:
          description: Error
      tags:
        - Shipping
      security:
        - api_key: [ 'shipping-read' ]


components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateShippingRequest:
      type: object
      properties:
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
            - INTERNATIONAL_DELIVERY
          description: Type of delivery
        country:
          type: string
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        message:
          type: string
          description: Message to display to customer
          nullable: true
        street:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true

    CreateShippingResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping created

    UpdateShippingAttributeRequest:
      type: object
      properties:
        value:
          type: string
          description: Value of the attribute
          nullable: true

    Shipping:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping method
        accountId:
          type: integer
          format: int64
          description: ID of the merchant
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        message:
          type: string
          description: Message to display to customer
          nullable: true
        enabled:
          type: boolean
          description: Enabled or Disabled
        rate:
          type: number
          format: double
          description: Detault Rate
          nullable: true
        currency:
          type: string
          description: Currency
        deliveryTime:
          type: integer
          description: Delivery Time in hours
          nullable: true
        country:
          type: string
          nullable: true
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        street:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true


    GetShippingResponse:
      type: object
      properties:
        shipping:
          type: object
          $ref: "#/components/schemas/Shipping"

    ShippingSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the shipping method
        accountId:
          type: integer
          format: int64
          description: ID of the merchant
        type:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        enabled:
          type: boolean
          description: Enabled or Disabled
        rate:
          type: number
          format: double
          description: Detault Rate
          nullable: true
        currency:
          type: string
          description: Currency
        deliveryTime:
          type: integer
          description: Delivery Time in hours
          nullable: true
        country:
          type: string
          nullable: true
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        street:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true

    ListShippingResponse:
      type: object
      properties:
        shippings:
          type: array
          items:
            $ref: "#/components/schemas/ShippingSummary"


    Product:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the shipping
        productType:
          type: string
          enum:
            - PHYSISCAL
            - NUMERIC
        quantity:
          type: integer
          description: Quantity of items
          minimum: 1

    SearchRateRequest:
      type: object
      properties:
        shippingId:
          type: integer
          format: int64
          nullable: true
        accountId:
          type: integer
          format: int64
        country:
          type: string
        cityId:
          type: integer
          format: int64
          description: ID of the location
          nullable: true
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
      required:
        - country
        - products

    SearchRateResponse:
      type: object
      properties:
        rates:
          type: array
          items:
            $ref: "#/components/schemas/RateSummary"

    RateSummary:
      type: object
      properties:
        shippingId:
          type: integer
          format: int64
          description: ID of the shipping method
        shippingType:
          type: string
          enum:
            - LOCAL_PICKUP
            - LOCAL_DELIVERY
            - EMAIL_DELIVERY
          description: Type of delivery
        rate:
          type: number
          format: double
          description: Detault Rate
        currency:
          type: string
          description: Currency
        deliveryTime:
          type: integer
          description: Delivery Time in hours
          nullable: true
